const S={
  tagline:["Scegliete una gara, comprate gli animali all'asta, si vede chi ha costruito la squadra giusta.",
           "Pick a contest, buy animals at auction, see who built the right team."],
  tuoNome:["Il tuo nome","Your name"],comeTiChiamano:["Come ti chiamano","What they call you"],
  creaStanza:["Crea una stanza","Create a room"],entraCodice:["Entra con un codice","Join with a code"],
  unTelefono:["Giocate su un telefono solo","Play on one phone"],
  offline:["Sei offline: si può giocare solo su un telefono solo.","You're offline: only one-phone mode works."],
  entraTitolo:["Entra nella stanza","Join the room"],indietro:["Indietro","Back"],
  chiediCodice:["Chiedi il codice a chi ha creato la partita.","Ask the code from whoever created the game."],
  collegati:["Collegati","Connect"],miCollego:["Mi collego…","Connecting…"],
  nessunaRisposta:["Nessuna risposta. Controlla il codice e che l'altro abbia l'app aperta.","No answer. Check the code and that they still have the app open."],
  nessunaStanza:["Nessuna stanza con questo codice.","No room with that code."],
  connessioneKO:["Connessione non riuscita. Riprova.","Connection failed. Try again."],
  stanzaPiena:["La stanza è piena.","The room is full."],giaIniziata:["La partita è già cominciata.","The game already started."],
  stanza:["Stanza","Room"],esci:["Esci","Leave"],
  codiceAgliAltri:["Codice da dare agli altri","Code to share"],
  postoLibero:["Posto libero","Free seat"],tieneStanza:["tiene la stanza","hosting"],
  pronto:["pronto","ready"],disconnesso:["disconnesso","disconnected"],tu:["tu","you"],
  quantiSiete:["Quanti siete intorno al telefono","How many of you around the phone"],
  creditiATesta:["Crediti a testa","Credits each"],laGara:["La gara","The contest"],
  scrivilaTu:["Scrivila tu","Write your own"],esCustom:["es. gara di tuffi sincronizzati","e.g. synchronised diving"],
  animaliSquadra:["Animali per squadra","Animals per team"],usaQuesta:["Usa questa gara","Use this contest"],
  apriAsta:["Apri l'asta","Open the auction"],
  aspettando:["Aspettando che %s scelga la gara.","Waiting for %s to pick the contest."],
  chiCreato:["chi ha creato la stanza","the host"],
  aTesta:["a testa","each"],allAsta:["all'asta","in the auction"],giocatori:["giocatori","players"],
  assegnati:["%d di %d assegnati","%d of %d taken"],
  apparizioneRara:["apparizione rara","rare sighting"],
  nessunaOfferta:["nessuna offerta","no bid"],offertaDi:["offerta: %d — %s","bid: %d — %s"],
  apriA1:["Apro a 1","I open at 1"],saltaAnimale:["Salta questo animale (skip)","Skip this animal"],
  skipUsato:["Skip già usato","Skip already used"],
  bannerApri:["Apri l'asta a 1 credito, o salta l'animale.","Open at 1 credit, or skip the animal."],
  avanzati:["avanzati","left"],
  info:["Info","Info"],
  infoGare:["Le gare","The contests"],
  infoGareD:["Cosa conta in ognuna, e chi ci può partecipare","What counts in each one, and who can take part"],
  infoAnimali:["Gli animali","The animals"],
  infoAnimaliD:["Scheda per scheda, con tutte le doti","Card by card, with every trait"],
  infoRegoleD:["Le regole dell'asta","How the auction works"],
  infoStanzaD:["Come funziona giocare in più telefoni","How playing across phones works"],
  infoAiD:["Il racconto della gara, se vuoi","The write-up of the contest, if you want it"],
  infoGareLead:["Ogni gara pesa doti diverse. Un numero alto vuol dire che quella dote conta molto; un numero negativo vuol dire che lì è un difetto.","Each contest weighs different traits. A high number means it matters a lot; a negative one means it's a handicap there."],
  ammessiSolo:["Ci possono partecipare solo gli animali con %s.","Only animals with %s can take part."],
  intesa:["Intesa","Chemistry"],
  intesaAlta:["ottima","excellent"],
  intesaMedia:["discreta","decent"],
  intesaBassa:["scarsa","poor"],
  intesaSimili:["rende di più se gli animali si somigliano in %s. Fino a +%d% di bonus.","it works better when the animals are alike in %s. Up to +%d% bonus."],
  intesaRuoli:["circa %d su %d con %s da %d in su, gli altri più piccoli. Fino a +%d% di bonus.","about %d of %d with %s at %d or more, the rest smaller. Up to +%d% bonus."],
  intesaNessuna:["nessuna. Qui conta solo quanto vale ciascuno.","none. Here only individual quality counts."],
  votoMedio:["voto medio %s","average rating %s"],
  senzaIntesa:["senza bonus intesa","no chemistry bonus"],
  cercaAnimale:["Cerca un animale","Search an animal"],
  nessunaGara:["Nessuna gara: solo le doti","No contest: traits only"],
  schedarioNota:["Scegli una gara per vedere quanto vale ognuno lì dentro.","Pick a contest to see what each animal is worth in it."],
  nonAmmesso:["fuori","not eligible"],
  nessunAnimale:["Nessun animale con questo nome.","No animal by that name."],
  mostraValori:["Valori degli animali","Animal ratings"],
  valoriSi:["Visibili","Shown"],
  valoriNo:["Nascosti","Hidden"],
  valoriSiD:["Durante l'asta si vedono le doti che contano e il voto dell'animale in quella gara.","During the auction you see the traits that matter and the animal's rating for that contest."],
  valoriNoD:["Si offre a occhio: nome ed emoji, niente numeri.","You bid by eye: name and emoji, no numbers."],
  offri:["Offri","Bid"],
  quantoOffri:["da %d a %d","%d to %d"],
  offertaFuori:["deve stare fra %d e %d","must be between %d and %d"],
  ancoraNiente:["Ancora nessun animale.","No animals yet."],
  vediRose:["Tocca le plance per vedere tutte le rose","Tap the boards to see everyone's teams"],
  versioniDiverse:["Versioni diverse: tu hai %s, la stanza ha %s. Ricaricate la pagina tutti e due.","Different versions: you have %s, the room has %s. Both of you reload."],
  versione:["Versione","Version"],
  aggiornaGioco:["Forza l'aggiornamento","Force an update"],
  sto_aggiornando:["Sto aggiornando…","Updating…"],
  fase_servizio:["Contatto il servizio…","Contacting the service…"],
  fase_stanza:["Servizio raggiunto. Cerco la stanza…","Service reached. Looking for the room…"],
  fase_presentazione:["Stanza trovata. Mi presento…","Room found. Saying hello…"],
  bloccato_servizio:["Non riesco a raggiungere il servizio che mette in contatto i dispositivi. Controlla la connessione.","Can't reach the service that introduces devices. Check your connection."],
  bloccato_stanza:["Il servizio risponde, ma non riesco ad aprire il canale con l'altro dispositivo. Provate a stare sulla stessa rete WiFi.","The service answers, but the channel won't open. Try the same WiFi."],
  bloccato_presentazione:["Canale aperto ma nessuna risposta. L'altro potrebbe avere una versione diversa.","Channel open but no answer. The other device may be on a different version."],
  passo:["Passo","Pass"],tutto:["TUTTO","ALL IN"],
  puoiArrivare:["Puoi arrivare a %d","You can go up to %d"],
  tiServono:[" (te ne servono %d per gli altri slot)"," (%d reserved for your empty slots)"],
  toccaA:["Tocca a %s.","%s's turn."],seiInTesta:["Sei in testa. Aspetta che qualcuno rilanci.","You're winning. Wait for a counter-bid."],
  haiPassato:["Hai passato su questo animale.","You passed on this animal."],
  nonPuoi:["Non puoi arrivare all'offerta.","You can't reach the bid."],
  rosaPiena:["Hai già la squadra completa.","Your team is already full."],
  venduto:["Venduto","Sold"],aPer:["a %s per %d","to %s for %d"],
  prossimo:["Prossimo animale","Next animal"],avanti:["Avanti","Next"],
  saltato:["Saltato","Skipped"],
  haUsatoSkip:["%s ha usato lo skip. L'animale esce dall'asta, ne entrano 3 nuovi.","%s used the skip. The animal leaves the auction, three new ones come in."],
  astaChiusa:["Asta<br>chiusa","Auction<br>closed"],
  squadrePronte:["%s — %d squadre pronte.","%s — %d teams ready."],
  creditiAvanzati:["%d crediti avanzati","%d credits left"],
  creditiRound:["Per round","Per round"],
  creditiTot:["Cumulativi","One budget"],
  altraCifra:["Altra cifra","Other amount"],
  usaCifra:["Usa","Use"],
  notaRound:["Ogni giocatore riceve %d crediti all'inizio di ogni round.","Each player gets %d credits at the start of every round."],
  notaTot:["Ogni giocatore ha %d crediti per tutta la partita: quello che avanza resta per i round dopo.","Each player has %d credits for the whole match: whatever is left carries over."],
  inTutto:["in tutto","in total"],
  aRound:["a round","per round"],
  inCassa:["%d in cassa","%d in the bank"],
  apriA:["Apro a %d","I open at %d"],
  bannerApriZero:["Sei a secco: puoi solo prenderlo se non lo vuole nessuno.","You're broke: you can only take it if nobody else wants it."],
  credito:["credito","credit"],crediti:["crediti","credits"],
  classifica:["Classifica","Standings"],
  affare:["Affare","Best value"],disastro:["Disastro","Worst buy"],
  puntiForti:["Forte in %s.","Strong in %s."],
  scoperta:["Scoperta in %s.","Weak in %s."],
  spiega:["Il punteggio è la media dei voti dei tuoi animali in questa gara, più una percentuale di bonus se la squadra sta bene insieme. Nella sezione Info trovi cosa conta in ogni gara.",
          "The score is the average rating of your animals for this contest, plus a percentage bonus if the team fits together. The Info section explains what counts in each contest."],
  chiediAI:["Fatti commentare la gara dall'AI","Get an AI commentary"],
  aiSimula:["Sta raccontando la gara.<br>Può volerci una ventina di secondi.","Writing up the contest.<br>This can take twenty seconds."],
  aiHost:["Il commento lo lancia chi tiene la stanza.","Only the host can start the commentary."],
  cronaca:["La cronaca","The story"],mvp:["MVP","MVP"],flop:["Flop","Flop"],
  tornaInizio:["Torna all'inizio","Back to start"],
  impostazioni:["Impostazioni","Settings"],chiudi:["Chiudi","Close"],lingua:["Lingua","Language"],
  commentoAI:["Commento dell'AI","AI commentary"],
  aiClaude:["Attivo tramite Claude. Non serve nessuna chiave.","Running through Claude. No key needed."],
  aiChiave:["Attivo con la tua chiave API.","Running on your API key."],
  aiSpento:["Spento. Il verdetto viene comunque calcolato dal gioco.","Off. The game still works out the verdict on its own."],
  notaChiave:["Serve una chiave API di Anthropic, e serve solo a chi crea la stanza. Resta salvata su questo dispositivo.",
              "Needs an Anthropic API key, and only the host needs one. It stays on this device."],
  salva:["Salva","Save"],rimuovi:["Rimuovi","Remove"],salvata:["Salvata.","Saved."],
  comeSiGioca:["Come si gioca","How it works"],
  regole:["Chi apre il giro deve offrire 1 credito, oppure usare il suo unico skip: in quel caso l'animale esce dall'asta, ne entrano tre nuovi, e tocca aprire al giocatore successivo.<br><br>Nella stanza, appena l'asta si apre tutti possono rilanciare quando vogliono: ogni rilancio fa ripartire il timer, e all'azzerarsi l'animale va a chi ha l'offerta più alta.<br><br>Puoi offrire al massimo i crediti che ti restano meno uno per ogni slot ancora vuoto, così finisci sempre la squadra.",
          "Whoever opens the round must bid 1 credit, or burn their single skip: the animal then leaves the auction, three new ones come in, and the next player opens.<br><br>In a room, once bidding opens anyone can raise at any time: every raise restarts the timer, and when it runs out the animal goes to the highest bid.<br><br>You can bid at most your credits minus one for every empty slot, so you always finish your team."],
  notaStanza:["Chi crea la stanza tiene la partita: se chiude l'app, la partita finisce. Gli altri possono rientrare con lo stesso codice e lo stesso nome.",
              "The host holds the game: if they close the app, the game ends. Others can rejoin with the same code and name."],
  azzera:["Cancella tutto e ricomincia","Erase everything and restart"],
  partitaMeta:["C'è una partita lasciata a metà","There's an unfinished game"],
  riprendi:["Riprendi","Resume"],buttaVia:["Butta via","Discard"],
  giaAssegnati:["%s — %d animali già assegnati (un telefono solo).","%s — %d animals already taken (one phone)."],
  stanzaChiusa:["La stanza si è chiusa.","The room closed."],
  servizioKO:["Connessione al servizio non riuscita. Riprova o gioca su un telefono solo.","Could not reach the matchmaking service. Retry, or play on one phone."],
  errChiave:["La chiave API non è valida o è scaduta.","The API key is invalid or expired."],
  errRete:["Non riesco a raggiungere il servizio.","Can't reach the service."],
  errPermesso:["Non hai dato il permesso di usare Claude qui.","You haven't allowed Claude here."],
  errTroppe:["Troppe richieste. Aspetta un minuto.","Too many requests. Wait a minute."],
  errJson:["La risposta è arrivata storta. Riprova.","The answer came back malformed. Try again."],
  errRifiuto:["L'AI non se l'è sentita di rispondere.","The AI declined to answer."],
  errGenerico:["Qualcosa è andato storto. Riprova tra poco.","Something went wrong. Try again shortly."],
  inventaAI:["Fatti inventare una gara dall'AI","Let the AI invent a contest"],
  inventando:["Sto inventando…","Inventing…"],qualcheSecondo:["Ci vuole qualche secondo","Give it a few seconds"],
  animaliPronti:["%d animali pronti.","%d animals ready."],
  garaPersonalizzata:["gara personalizzata","custom contest"],
  garaMisteriosa:["Gara misteriosa","Mystery contest"]
};

S.creandoStanza=["Sto aprendo la stanza…","Opening the room…"];
S.riprovo=["Riprovo… (%d)","Retrying… (%d)"];
S.riprova=["Riprova","Try again"];
S.iniziaCon=["Inizia lo stesso (%d di %d)","Start anyway (%d of %d)"];
S.inSala=["In sala: %d di %d","In the room: %d of %d"];
S.numeroGiocatori=["Quanti giocatori","How many players"];
S.puntiPerVincere=["Punti per vincere","Points to win"];
S.vittoria=["vittoria","win"];
S.vittorie=["vittorie","wins"];
S.sceltaGara=["Chi sceglie la gara","Who picks the contest"];
S.sceltaTurno=["A turno","Take turns"];
S.sceltaTurnoD=["Ogni round sceglie un giocatore diverso","A different player picks each round"];
S.sceltaCaso=["A sorte","At random"];
S.sceltaCasoD=["La estrae il gioco","The game draws it"];
S.round=["Round %d","Round %d"];
S.primoA=["Vince chi arriva a %d","First to %d wins"];
S.tocchiTeScegliere=["Tocca a te scegliere la gara","Your turn to pick the contest"];
S.sceglieLui=["Sta scegliendo %s","%s is picking"];
S.attendiScelta=["Aspetta la sua scelta.","Wait for their pick."];
S.roundVinto=["Round %d a %s","Round %d goes to %s"];
S.partitaFinita=["Partita<br>finita","Match<br>over"];
S.vinceLaPartita=["Vince la partita con %d round su %d.","Takes the match with %d rounds out of %d."];
S.prossimoRound=["Prossimo round","Next round"];
S.attendiRound=["Aspetta che venga aperto il prossimo round.","Wait for the next round to open."];
S.tornaHome=["Torna alla home","Back to home"];
S.chiudiStanza=["Uscendo, la stanza viene chiusa per tutti.","Leaving closes the room for everyone."];
S.punti=["Punti","Points"];
